### ISSUE TITLE
Integer: Uninitialized variable

### ISSUE THREAD

**Issue by lxconan** [niniaibu/java#2]
什么是未初始化的变量呢？Java 程序可以使用未初始化的变量么？

**Comment by niniaibu** [comment]
未初始化变量即未赋初值的变量，java程序中可以使用未初始化的变量，在类中定义的成员变量如果没有初始化，java会赋默认值，但是局部变量java虚拟机不会自动初始化为默认值，故必须经过显示的初始化。

**Comment by lxconan** [comment]
Correct!
