### ISSUE TITLE
Integer: Conversion

### ISSUE THREAD

**Issue by lxconan** [niniaibu/java#3]
所有的整数类型中，哪些类型可以 “隐式转换” 为其他的整数类型呢？

**Comment by niniaibu** [comment]
一个范围小的数值或变量赋值给另外一个范围大的变量时，可以自动转换（隐式转换）。byte(8bit)<short(16bit)<int(32bit)<long(64bit)<float(32bit)<double(64bit)

**Comment by lxconan** [comment]
Correct!
